apiVersion: v1
appVersion: 0.0.5
description: A Helm chart for Opensearch Curator
keywords:
- curator
- opensearch
- opensearch-curator
maintainers:
- email: mestdagh.tom@gmail.com
  name: tmestdagh
- email: gianrubio@gmail.com
  name: gianrubio
name: opencsearch-curator
